"use client";

import { useState, useMemo } from "react";

export default function ExcipientFinder() {
  const [dosageForm, setDosageForm] = useState("");
  const [subDosageForm, setSubDosageForm] = useState("");
  const [apiName, setApiName] = useState("");
  const [results, setResults] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [expandedResultId, setExpandedResultId] = useState<number | null>(null);

  // New States for Filtering and Pagination
  const [selectedCategory, setSelectedCategory] = useState<string>("All");
  const [currentPage, setCurrentPage] = useState<number>(1);
  const [generatingItemId, setGeneratingItemId] = useState<number | null>(null);
  const ITEMS_PER_PAGE = 10;

  const handleDownloadItemPDF = async (item: any) => {
    setGeneratingItemId(item.id);
    
    const container = document.createElement('div');
    container.style.padding = '40px';
    container.style.color = '#000000';
    container.style.backgroundColor = '#FFFFFF';
    container.style.fontFamily = 'Arial, Helvetica, sans-serif';
    container.style.width = '800px'; 
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '0';
    
    const displayApi = apiName || 'Not specified';
    const displayForm = `${dosageForm} ${subDosageForm ? `(${subDosageForm})` : ''}`;

    container.innerHTML = `
      <div style="border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 20px;">
        <h1 style="margin: 0 0 10px 0; font-size: 24px; color: #000;">Pharmamatch AI - Excipient Evaluation Report</h1>
        <p style="margin: 5px 0; font-size: 16px;"><strong>Active Pharmaceutical Ingredient (API):</strong> ${displayApi}</p>
        <p style="margin: 5px 0; font-size: 16px;"><strong>Target Dosage Form:</strong> ${displayForm}</p>
      </div>
      
      <div style="margin-bottom: 30px;">
        <h2 style="font-size: 20px; border-bottom: 1px solid #000; padding-bottom: 5px; margin-bottom: 15px;">Result Overview</h2>
        <p style="margin: 8px 0; font-size: 16px;"><strong>Excipient Name:</strong> ${item.name}</p>
        <p style="margin: 8px 0; font-size: 16px;"><strong>Functional Category:</strong> ${item.category}</p>
        <p style="margin: 8px 0; font-size: 16px;"><strong>Compatibility Score:</strong> ${item.compatibility}</p>
      </div>

      <div style="margin-bottom: 30px;">
        <h2 style="font-size: 18px; border-bottom: 1px solid #000; padding-bottom: 5px; margin-bottom: 15px;">Detailed Analysis</h2>
        <h3 style="font-size: 16px; margin-bottom: 5px;">General Literature Profile</h3>
        <p style="margin-top: 0; line-height: 1.5; text-align: justify; font-size: 15px;">${item.literature}</p>
        
        <h3 style="font-size: 16px; margin-top: 20px; margin-bottom: 5px;">AI Generated Summary</h3>
        <p style="margin-top: 0; line-height: 1.5; text-align: justify; font-size: 15px;">${item.summary}</p>
      </div>

      <div style="margin-bottom: 30px;">
        <h2 style="font-size: 18px; border-bottom: 1px solid #000; padding-bottom: 5px; margin-bottom: 15px;">References & Literature</h2>
        <h3 style="font-size: 16px; margin-bottom: 5px;">Database Reference</h3>
        <p style="margin-top: 0; font-size: 15px;"><a href="${item.link}" style="color: #000; text-decoration: underline;">${item.reference}</a></p>
        
        <h3 style="font-size: 16px; margin-top: 20px; margin-bottom: 5px;">Research Papers</h3>
        <ul style="margin-top: 0; padding-left: 20px; font-size: 15px;">
          ${item.papers && item.papers.length > 0 ? item.papers.map((p: any) => `
            <li style="margin-bottom: 10px; line-height: 1.4;">
              <strong>[${p.source}]</strong> ${p.title}<br/>
              <a href="${p.link}" style="color: #000; text-decoration: underline; font-size: 13px;">${p.link}</a>
            </li>
          `).join('') : '<li>No specific papers found.</li>'}
        </ul>
      </div>
      
      <div style="margin-top: 50px; font-size: 12px; color: #333; text-align: center; border-top: 1px solid #000; padding-top: 10px;">
        Generated by Pharmamatch AI Pre-formulation Engine
      </div>
    `;

    document.body.appendChild(container);

    try {
      const opt = {
        margin:       [15, 15, 15, 15],
        filename:     `${item.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.pdf`,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true, logging: false },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };
      
      const html2pdfModule = await import('html2pdf.js');
      const html2pdf = html2pdfModule.default ? html2pdfModule.default : html2pdfModule;
      
      await html2pdf().set(opt).from(container).save();
    } catch (error) {
      console.error("Error generating PDF:", error);
    } finally {
      document.body.removeChild(container);
      setGeneratingItemId(null);
    }
  };

  const getSubDosageOptions = () => {
    switch(dosageForm) {
      case "tablets": return [
        "Immediate Release (IR)", 
        "Extended Release (ER/XR/SR)", 
        "Delayed Release (Enteric Coated)", 
        "Chewable Tablets", 
        "Sublingual Tablets", 
        "Buccal Tablets", 
        "Effervescent Tablets", 
        "Orally Disintegrating Tablets (ODT)", 
        "Lozenges / Pastilles",
        "Film Coated Tablets",
        "Sugar Coated Tablets",
        "Multi-layer / Bilayer Tablets",
        "Implantable Tablets",
        "Vaginal Tablets"
      ];
      case "capsules": return [
        "Hard Gelatin Capsules (Powder/Granule)", 
        "Hard Gelatin Capsules (Pellet/Microparticle)", 
        "Hard Gelatin Capsules (Liquid-filled)", 
        "Soft Gelatin Capsules", 
        "Enteric Coated Capsules", 
        "Sustained Release Capsules",
        "Plant-based / HPMC Capsules"
      ];
      case "powders": return [
        "Bulk Powders (Oral)", 
        "Bulk Powders (External/Dusting)", 
        "Divided Powders (Sachets)", 
        "Effervescent Powders", 
        "Insufflations", 
        "Dry Powders for Inhalation (DPI)", 
        "Lyophilized Powders for Injection", 
        "Powders for Reconstitution (Oral Suspensions)"
      ];
      case "liquids": return [
        "Oral Monophasic - Solutions", 
        "Oral Monophasic - Syrups", 
        "Oral Monophasic - Elixirs", 
        "Oral Monophasic - Linctuses / Draughts", 
        "Oral Monophasic - Drops", 
        "Oral Biphasic - Emulsions", 
        "Oral Biphasic - Suspensions", 
        "Topical - Lotions",
        "Topical - Liniments",
        "Topical - Collodions / Paints",
        "Mucosal - Gargles / Mouthwashes",
        "Mucosal - Ear Drops / Eye Drops / Nasal Drops",
        "Parenterals - Intravenous (IV)", 
        "Parenterals - Intramuscular (IM)",
        "Parenterals - Subcutaneous (SC)",
        "Parenterals - Intradermal (ID)",
        "Parenterals - Intrathecal / Epidural",
        "Parenterals - Large Volume Parenterals (LVP)",
        "Parenterals - Small Volume Parenterals (SVP)"
      ];
      case "semisolids": return [
        "Ointments - Oleaginous Base", 
        "Ointments - Absorption Base", 
        "Ointments - Water-Removable Base", 
        "Ointments - Water-Soluble Base", 
        "Creams - Oil-in-Water (O/W)", 
        "Creams - Water-in-Oil (W/O)", 
        "Pastes", 
        "Gels - Hydrogels",
        "Gels - Organogels",
        "Poultices / Cataplasms",
        "Plasters / Transdermal Patches"
      ];
      case "suppositories": return [
        "Rectal Suppositories", 
        "Vaginal Pessaries", 
        "Urethral Bougies",
        "Ear Cones",
        "Nasal Bougies"
      ];
      default: return [];
    }
  };

  const getMockResults = (form: string, subForm: string, api: string) => {
    // Base static data for realistic names and extensive results
    const excipientBase = [
      { name: "Microcrystalline Cellulose (MCC)", category: "Diluent", formTags: ["tablets", "capsules", "powders"] },
      { name: "Lactose Monohydrate", category: "Diluent", formTags: ["tablets", "capsules", "powders"] },
      { name: "Magnesium Stearate", category: "Lubricant", formTags: ["tablets", "capsules", "powders"] },
      { name: "Talc", category: "Glidant", formTags: ["tablets", "capsules", "powders"] },
      { name: "Maize Starch", category: "Disintegrant", formTags: ["tablets", "capsules", "powders"] },
      { name: "Croscarmellose Sodium", category: "Disintegrant", formTags: ["tablets", "capsules"] },
      { name: "Sodium Starch Glycolate", category: "Disintegrant", formTags: ["tablets", "capsules"] },
      { name: "Povidone (PVP)", category: "Binder", formTags: ["tablets", "capsules", "powders"] },
      { name: "Hydroxypropyl Methylcellulose (HPMC)", category: "Binder", formTags: ["tablets", "capsules"] },
      { name: "Dibasic Calcium Phosphate", category: "Diluent", formTags: ["tablets", "capsules", "powders"] },
      { name: "Colloidal Silicon Dioxide", category: "Glidant", formTags: ["tablets", "capsules", "powders"] },
      { name: "Stearic Acid", category: "Lubricant", formTags: ["tablets", "capsules"] },
      { name: "Mannitol", category: "Diluent", formTags: ["tablets", "capsules", "powders"] },
      { name: "Sodium Lauryl Sulfate", category: "Lubricant", formTags: ["tablets", "capsules"] },
      { name: "Propylene Glycol", category: "Solvent", formTags: ["liquids", "semisolids"] },
      { name: "Glycerin", category: "Solvent", formTags: ["liquids", "semisolids"] },
      { name: "Polysorbate 80 (Tween 80)", category: "Emulsifier", formTags: ["liquids", "semisolids"] },
      { name: "Water for Injection (WFI)", category: "Solvent", formTags: ["liquids"] },
      { name: "Benzyl Alcohol", category: "Preservative", formTags: ["liquids", "semisolids"] },
      { name: "Methylparaben", category: "Preservative", formTags: ["liquids", "semisolids"] },
      { name: "Propylparaben", category: "Preservative", formTags: ["liquids", "semisolids"] },
      { name: "White Petrolatum", category: "Base", formTags: ["semisolids"] },
      { name: "Cetostearyl Alcohol", category: "Emulsifier", formTags: ["semisolids"] },
      { name: "Carbomer 940", category: "Thickening Agent", formTags: ["semisolids", "liquids"] },
      { name: "Cocoa Butter", category: "Base", formTags: ["suppositories"] },
      { name: "Polyethylene Glycol (PEG 400)", category: "Solvent", formTags: ["liquids", "semisolids"] },
      { name: "Polyethylene Glycol (PEG 4000/6000)", category: "Base", formTags: ["suppositories", "tablets", "semisolids"] },
      { name: "Xanthan Gum", category: "Thickening Agent", formTags: ["liquids", "semisolids"] },
      { name: "Sodium Benzoate", category: "Preservative", formTags: ["liquids"] },
      { name: "Sorbitol", category: "Diluent", formTags: ["liquids", "tablets"] },
      { name: "Sucrose", category: "Diluent", formTags: ["liquids", "tablets", "powders"] },
      { name: "Tragacanth", category: "Thickening Agent", formTags: ["liquids", "semisolids"] },
      { name: "Sodium Alginate", category: "Thickening Agent", formTags: ["liquids", "semisolids"] },
      { name: "Cera Alba (White Beeswax)", category: "Base", formTags: ["semisolids"] },
      { name: "Liquid Paraffin", category: "Base", formTags: ["semisolids"] },
      { name: "Opadry", category: "Coating Agent", formTags: ["tablets"] },
      { name: "Eudragit", category: "Coating Agent", formTags: ["tablets", "capsules"] },
      { name: "Titanium Dioxide", category: "Colorant", formTags: ["tablets", "capsules", "semisolids"] },
      { name: "Iron Oxide Red", category: "Colorant", formTags: ["tablets", "capsules"] },
      { name: "Aspartame", category: "Flavoring Agent", formTags: ["liquids", "tablets", "powders"] },
      { name: "Saccharin Sodium", category: "Flavoring Agent", formTags: ["liquids", "tablets", "powders"] }
    ];

    // Filter based on dosage form
    let applicableBase = excipientBase.filter(e => e.formTags.includes(form));
    
    // If no specific match, use all to guarantee results
    if(applicableBase.length === 0) applicableBase = excipientBase;

    const displayApi = api ? api : "Active Pharmaceutical Ingredient";
    const displayForm = subForm ? subForm : form;

    // Generate mock results from applicable base
    const mockData = applicableBase.map((item, idx) => {
      // Generate random match score > 50, but we can salt it with the API string length to make it pseudo-deterministic
      const salt = (api.length * item.name.length) % 30;
      const matchScore = Math.min(99, Math.max(51, 60 + salt + Math.floor(Math.random() * 20))); 
      
      // Generate 1 to 3 direct paper references per excipient
      const numPapers = Math.floor(Math.random() * 3) + 1; 
      const papers = [];
      
      for(let i=0; i<numPapers; i++) {
        const isGoogleScholar = i % 2 !== 0; // Alternate between PubMed and Google Scholar
        
        let title = "";
        if (i === 0) {
            title = `Compatibility study of ${displayApi} with ${item.name} in ${displayForm} formulations`;
        } else if (i === 1) {
            title = `Influence of ${item.name} as a ${item.category} on the release kinetics of ${displayApi}`;
        } else {
            title = `Preformulation compatibility screening of ${displayApi} using ${item.name}`;
        }

        papers.push({
          id: `paper-${idx}-${i}`,
          title: title,
          source: isGoogleScholar ? "Google Scholar" : "PubMed",
          link: isGoogleScholar 
            ? `https://scholar.google.com/scholar?q=${encodeURIComponent(title)}`
            : `https://pubmed.ncbi.nlm.nih.gov/?term=${encodeURIComponent(title)}`
        });
      }
      
      return {
        id: idx + 1,
        name: item.name,
        category: item.category,
        compatibility: `${matchScore}%`,
        matchScore: matchScore,
        literature: `Demonstrated excellent physicochemical compatibility with ${displayApi}. Evaluated specifically for ${displayForm} to ensure optimal ${item.category.toLowerCase()} functionality.`,
        reference: `PubChem / Handbook ID: ${10000 + idx * 7}`,
        link: `https://pubchem.ncbi.nlm.nih.gov/compound/${10000 + idx * 7}`,
        summary: `A comprehensive evaluation of ${item.name} interacting with ${displayApi}. The study outlines the absence of major physicochemical interactions and highlights the optimal concentration ranges in ${displayForm} to achieve maximum shelf-life stability (Compatibility Match: ${matchScore}%).`,
        papers: papers
      };
    });

    // Sort by match score descending
    return mockData.sort((a, b) => b.matchScore - a.matchScore);
  };

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setExpandedResultId(null);
    setCurrentPage(1);
    setSelectedCategory("All");
    
    setTimeout(() => {
      setResults(getMockResults(dosageForm, subDosageForm, apiName));
      setLoading(false);
    }, 1500);
  };

  // Pagination & Filtering Logic
  const availableCategories = useMemo(() => {
    const cats = new Set(results.map(r => r.category));
    return ["All", ...Array.from(cats)].sort();
  }, [results]);

  const filteredResults = useMemo(() => {
    if (selectedCategory === "All") return results;
    return results.filter(r => r.category === selectedCategory);
  }, [results, selectedCategory]);

  const totalPages = Math.ceil(filteredResults.length / ITEMS_PER_PAGE);
  
  const paginatedResults = useMemo(() => {
    const startIndex = (currentPage - 1) * ITEMS_PER_PAGE;
    return filteredResults.slice(startIndex, startIndex + ITEMS_PER_PAGE);
  }, [filteredResults, currentPage]);

  return (
    <div className="animate-fade-in">
      <div className="tool-header">
        <h1>Excipient Finder & Compatibility</h1>
        <p>AI-driven excipient recommendation based on dosage form and API.</p>
      </div>

      <div className="glass-panel">
        <form onSubmit={handleSearch}>
          <div className="grid grid-cols-3">
            <div className="form-group">
              <label className="form-label">Dosage Form</label>
              <select className="form-select" value={dosageForm} onChange={(e) => { setDosageForm(e.target.value); setSubDosageForm(""); }} required>
                <option value="">-- Select Form --</option>
                <option value="tablets">Tablets</option>
                <option value="capsules">Capsules</option>
                <option value="powders">Powder / Granules</option>
                <option value="liquids">Liquid Dosage Forms</option>
                <option value="semisolids">Semi-Solid Dosage Forms</option>
                <option value="suppositories">Suppositories & Pessaries</option>
              </select>
            </div>

            <div className="form-group animate-fade-in">
              <label className="form-label">Subdosage Form</label>
              <select className="form-select" value={subDosageForm} onChange={(e) => setSubDosageForm(e.target.value)} disabled={!dosageForm} required>
                <option value="">-- Specific Details --</option>
                {getSubDosageOptions().map(opt => <option key={opt} value={opt}>{opt}</option>)}
              </select>
            </div>
            
            <div className="form-group">
              <label className="form-label">API / CAS Number</label>
              <input 
                type="text" 
                className="form-input" 
                placeholder="e.g. Paracetamol" 
                value={apiName}
                onChange={(e) => setApiName(e.target.value)}
                required
              />
            </div>
          </div>
          <button type="submit" className="btn btn-primary" disabled={loading}>
            {loading ? "Analyzing databases..." : "Find Compatible Excipients"}
          </button>
        </form>
      </div>

      {results.length > 0 && (
        <div className="results-panel animate-fade-in" style={{ marginTop: '2rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem', flexWrap: 'wrap', gap: '1rem' }}>
            <h3 style={{ margin: 0 }}>AI Recommendations ({filteredResults.length} Excipients Found)</h3>
          </div>
          
          {/* Category Filter */}
          <div className="filter-container" style={{ marginBottom: '1.5rem' }}>
            <h4 style={{ marginBottom: '0.75rem', fontSize: '0.9rem', color: 'var(--text-secondary)' }}>Filter by Excipient Category:</h4>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
              {availableCategories.map(cat => {
                const count = cat === "All" ? results.length : results.filter(r => r.category === cat).length;
                const isSelected = selectedCategory === cat;
                return (
                  <button
                    key={cat}
                    onClick={() => { setSelectedCategory(cat); setCurrentPage(1); }}
                    style={{ 
                      padding: '0.4rem 1rem',
                      borderRadius: '999px',
                      fontSize: '0.85rem',
                      transition: 'all 0.2s ease',
                      cursor: 'pointer',
                      backgroundColor: isSelected ? 'var(--accent-color)' : 'rgba(255,255,255,0.05)',
                      color: isSelected ? '#000' : 'var(--text-primary)',
                      border: `1px solid ${isSelected ? 'var(--accent-color)' : 'rgba(255,255,255,0.1)'}`,
                      fontWeight: isSelected ? '600' : '400'
                    }}
                  >
                    {cat} <span style={{ opacity: 0.7, marginLeft: '0.2rem' }}>({count})</span>
                  </button>
                )
              })}
            </div>
          </div>

          <p style={{ marginBottom: '1rem', color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
            Click on a recommendation to view the paper summary.
          </p>

          <div style={{ minHeight: '400px' }}>
            {paginatedResults.length === 0 ? (
              <p style={{ color: 'var(--text-secondary)', textAlign: 'center', padding: '2rem 0' }}>No excipients found for this category.</p>
            ) : (
              paginatedResults.map((item, index) => (
                <div 
                  key={item.id} 
                  className={`result-item delay-${(index % ITEMS_PER_PAGE + 1) * 50} animate-fade-in`}
                  onClick={() => setExpandedResultId(expandedResultId === item.id ? null : item.id)}
                  style={{ cursor: 'pointer', transition: 'all 0.3s ease' }}
                >
                  <div className="result-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span className="result-title">{item.name}</span>
                    <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
                      <button 
                        onClick={(e) => { e.stopPropagation(); handleDownloadItemPDF(item); }}
                        disabled={generatingItemId === item.id}
                        style={{
                           padding: '0.2rem 0.6rem',
                           borderRadius: '4px',
                           fontSize: '0.75rem',
                           backgroundColor: 'rgba(255,255,255,0.1)',
                           color: '#fff',
                           border: '1px solid rgba(255,255,255,0.3)',
                           cursor: generatingItemId === item.id ? 'wait' : 'pointer',
                           display: 'flex',
                           alignItems: 'center',
                           gap: '0.3rem',
                           transition: 'all 0.2s ease'
                        }}
                      >
                        {generatingItemId === item.id ? '⏳' : '📥'} PDF Report
                      </button>
                      <span style={{ 
                        padding: '0.2rem 0.6rem', 
                        borderRadius: '4px', 
                        fontSize: '0.75rem', 
                        backgroundColor: 'rgba(0, 240, 255, 0.1)', 
                        color: 'var(--accent-color)', 
                        border: '1px solid rgba(0, 240, 255, 0.3)' 
                      }}>
                        {item.category}
                      </span>
                      <span className="compatibility-badge">Match: {item.compatibility}</span>
                    </div>
                  </div>
                  <p>{item.literature}</p>

                  {expandedResultId === item.id && (
                    <div className="animate-fade-in" style={{ 
                      marginTop: '1rem', 
                      padding: '1rem', 
                      backgroundColor: 'rgba(0, 240, 255, 0.05)', 
                      borderLeft: '3px solid var(--accent-color)',
                      borderRadius: '0 8px 8px 0'
                    }}>
                      <h4 style={{ color: 'var(--accent-color)', fontSize: '0.9rem', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                          <polyline points="14 2 14 8 20 8"></polyline>
                          <line x1="16" y1="13" x2="8" y2="13"></line>
                          <line x1="16" y1="17" x2="8" y2="17"></line>
                          <polyline points="10 9 9 9 8 9"></polyline>
                        </svg>
                        Paper Summary
                      </h4>
                      <p style={{ fontSize: '0.85rem', lineHeight: '1.5', color: 'var(--text-primary)' }}>
                        {item.summary}
                      </p>
                    </div>
                  )}

                  <div style={{ marginTop: '1rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }} onClick={(e) => e.stopPropagation()}>
                    <a href={item.link} target="_blank" rel="noopener noreferrer" className="reference-link" style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem' }}>
                      <span>🔗 Database Reference: {item.reference}</span>
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
                        <polyline points="15 3 21 3 21 9"></polyline>
                        <line x1="10" y1="14" x2="21" y2="3"></line>
                      </svg>
                    </a>
                    
                    {item.papers && item.papers.length > 0 && (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', marginTop: '0.25rem' }}>
                        <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.5px', fontWeight: 'bold' }}>Related Research Papers</span>
                        {item.papers.map((paper: any) => (
                          <a key={paper.id} href={paper.link} target="_blank" rel="noopener noreferrer" className="reference-link" style={{ display: 'inline-flex', alignItems: 'flex-start', gap: '0.5rem', color: '#00e5ff', fontSize: '0.85rem', lineHeight: '1.4' }}>
                            <span style={{ marginTop: '0.1rem' }}>📄</span>
                            <span style={{ flex: 1 }}><strong>[{paper.source}]</strong> {paper.title}</span>
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ marginTop: '0.2rem', flexShrink: 0 }}>
                              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
                              <polyline points="15 3 21 3 21 9"></polyline>
                              <line x1="10" y1="14" x2="21" y2="3"></line>
                            </svg>
                          </a>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Pagination Controls */}
          {totalPages > 1 && (
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '1rem', marginTop: '1.5rem', borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '1.5rem' }}>
              <button 
                onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                disabled={currentPage === 1}
                style={{ 
                  padding: '0.5rem 1rem', 
                  borderRadius: '4px', 
                  backgroundColor: currentPage === 1 ? 'rgba(255,255,255,0.05)' : 'rgba(255,255,255,0.1)', 
                  color: currentPage === 1 ? 'rgba(255,255,255,0.3)' : 'var(--text-primary)',
                  cursor: currentPage === 1 ? 'not-allowed' : 'pointer',
                  transition: 'all 0.2s ease'
                }}
              >
                Previous
              </button>
              
              <span style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
                Page {currentPage} of {totalPages}
              </span>
              
              <button 
                onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                disabled={currentPage === totalPages}
                style={{ 
                  padding: '0.5rem 1rem', 
                  borderRadius: '4px', 
                  backgroundColor: currentPage === totalPages ? 'rgba(255,255,255,0.05)' : 'rgba(255,255,255,0.1)', 
                  color: currentPage === totalPages ? 'rgba(255,255,255,0.3)' : 'var(--text-primary)',
                  cursor: currentPage === totalPages ? 'not-allowed' : 'pointer',
                  transition: 'all 0.2s ease'
                }}
              >
                Next
              </button>
            </div>
          )}
          
          <div className="glass-panel" style={{ marginTop: '2rem', borderColor: 'var(--accent-color)' }}>
            <h4 style={{ color: 'var(--accent-color)' }}>💡 Prototype Suggestion</h4>
            <p>Based on the selected {dosageForm} format, the recommended excipient profile provides optimal stability and release characteristics for {apiName || 'your active ingredient'}.</p>
          </div>
        </div>
      )}
    </div>
  );
}
